'use client'
import { CartItem } from '@/components/Type/CartItem';
import { useState } from 'react';
import '../styles/globals.scss'
import { Context } from './actions/context';

 const metadata = {
  title: 'Asteroid',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const [CartItems,setCartItems]=useState<CartItem[]>([]);//контекст для корзины
  return (
    <html lang="en">
      <body>
        <Context.Provider value={{CartItems,setCartItems}}>
          {children}
        </Context.Provider>
      </body>
    </html>
  )
}
